<<<<<<< HEAD
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Bullet : MonoBehaviour
{
    // ëړx
    public float MoveSpeed = 0.01f;
    Enemy enemy;
    Player_Bullet player_bullet;
    Familiar familiar;
   

    public static float Bullet_Power;

    // Start is called before the first frame update
    void Start()
    {
        Bullet_Power = 1.0f;
    }

    // Update is called once per frame
    void Update()
    {
        // |[Y͉Ȃ
        if (Mathf.Approximately(Time.timeScale, 0f))
            return;

        if (this.gameObject.name != "Prefab_Seeker")
        {
            // eړ
            this.transform.Translate(MoveSpeed, 0.0f, 0.0f);
        }

        // JOɏo폜
        if (!GetComponent<Renderer>().isVisible)
        {
            Destroy(this.gameObject);
        }
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.tag == "Enemy")
        {
            Score.AddScore(10/*enemy.GetEnemyScore()*/);// XRAZ
            Destroy(this.gameObject);      // obg폜
            Destroy(collision.gameObject); // G폜
            Player_ULT.AddUltCnt();        // KEZJEgZ
        }

    }
}
=======
>>>>>>> 228abb0 (背景スクロール差し替え)
